---
title: "Figures and tables in Simulation 1"
output: html_document
---

```{r}
file_list <- list.files(path = getwd(), pattern = "*.csv", full.names = TRUE)
data_list <- lapply(file_list, read.csv)
file_list <- basename(file_list)
```


```{r}
library(ggplot2)
library(latex2exp)
n_row <- nrow(data_list[[1]])

data_20_10_500 <- array(0, dim = c(4, 3, n_row, 3))
for (d1 in 1:4) {
  for (d2 in 1:3) {
    i <- (d1 - 1) * 3 + d2
    data_20_10_500[d1, d2, , ] <- as.matrix(data_list[[i]][, c("error1", "error2", "error3")])
  }
}

data_30_20_1000 <- array(0, dim = c(4, 3, n_row, 3))
for (d1 in 1:4) {
  for (d2 in 1:3) {
    i <- (d1 - 1) * 3 + d2 + 12
    data_30_20_1000[d1, d2, , ] <- as.matrix(data_list[[i]][, c("error1", "error2", "error3")])
  }
}


median_20_10_500 <- apply(data_20_10_500, c(1, 2, 4), median)
q1_20_10_500 <- apply(data_20_10_500, c(1, 2, 4), function(x) quantile(x, 0.25))
q3_20_10_500 <- apply(data_20_10_500, c(1, 2, 4), function(x) quantile(x, 0.75))


median_30_20_1000 <- apply(data_30_20_1000, c(1, 2, 4), median)
q1_30_20_1000 <- apply(data_30_20_1000, c(1, 2, 4), function(x) quantile(x, 0.25))
q3_30_20_1000 <- apply(data_30_20_1000, c(1, 2, 4), function(x) quantile(x, 0.75))



median_20_10_500_reordered <- aperm(median_20_10_500, c(3, 2, 1))
q3_20_10_500_reordered <- aperm(q3_20_10_500, c(3, 2, 1))
q1_20_10_500_reordered <- aperm(q1_20_10_500, c(3, 2, 1))
median_30_20_1000_reordered <- aperm(median_30_20_1000, c(3, 2, 1))
q3_30_20_1000_reordered <- aperm(q3_30_20_1000, c(3, 2, 1))
q1_30_20_1000_reordered <- aperm(q1_30_20_1000, c(3, 2, 1))


original_labels <- c("d1=0 d2=0", "d1=0 d2=1", "d1=0 d2=2", 
                   "d1=1 d2=0", "d1=1 d2=1", "d1=1 d2=2", 
                   "d1=2 d2=0", "d1=2 d2=1", "d1=2 d2=2", 
                   "d1=3 d2=0", "d1=3 d2=1", "d1=3 d2=2")
new_labels <- c(
  "d1=0 d2=0" = expression(d[1] == 0* "," ~ d[2] == 0),
  "d1=0 d2=1" = expression(d[1] == 0* "," ~ d[2] == 1),
  "d1=0 d2=2" = expression(d[1] == 0* "," ~ d[2] == 2),
  "d1=1 d2=0" = expression(d[1] == 1* "," ~ d[2] == 0),
  "d1=1 d2=1" = expression(d[1] == 1* "," ~ d[2] == 1),
  "d1=1 d2=2" = expression(d[1] == 1* "," ~ d[2] == 2),
  "d1=2 d2=0" = expression(d[1] == 2* "," ~ d[2] == 0),
  "d1=2 d2=1" = expression(d[1] == 2* "," ~ d[2] == 1),
  "d1=2 d2=2" = expression(d[1] == 2* "," ~ d[2] == 2),
  "d1=3 d2=0" = expression(d[1] == 3* "," ~ d[2] == 0),
  "d1=3 d2=1" = expression(d[1] == 3* "," ~ d[2] == 1),
  "d1=3 d2=2" = expression(d[1] == 3* "," ~ d[2] == 2)
)

data <- data.frame(
  x = factor(rep(original_labels, each = 3)),
  y = as.vector(median_20_10_500_reordered),
  ymin = as.vector(q1_20_10_500_reordered),
  ymax = as.vector(q3_20_10_500_reordered),
  group = rep(c("MAR", "RRMAR", "MARCF"), 12)
)

data$group <- factor(data$group, levels = c("MAR", "RRMAR", "MARCF"))

ggplot(data, aes(x = x, y = y, color = group)) +
  geom_point(shape = 4, size = 3, position = position_dodge(width = 0.5)) + 
  geom_errorbar(aes(ymin = ymin, ymax = ymax), 
                width = 0.2, position = position_dodge(width = 0.5)) + 
  scale_x_discrete(labels = new_labels) +
  theme_minimal() +
  labs(x = "", y = "Estimation error", color = "Model") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=11),
        legend.position = c(0, 1),
        legend.justification = c(0, 1),
        legend.background = element_rect(
          color = "black",
          linewidth = 0.05,
          linetype = "solid"
        ),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.key.size = unit(0.5, "cm")) 

ggsave("20_10_500_v2.pdf")

data <- data.frame(
  x = factor(rep(original_labels, each = 3)),
  y = as.vector(median_30_20_1000_reordered),
  ymin = as.vector(q1_30_20_1000_reordered),
  ymax = as.vector(q3_30_20_1000_reordered),
  group = rep(c("MAR", "RRMAR", "MARCF"), 12)
)

data$group <- factor(data$group, levels = c("MAR", "RRMAR", "MARCF"))

ggplot(data, aes(x = x, y = y, color = group)) +
  geom_point(shape = 4, size = 3, position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = ymin, ymax = ymax), 
                width = 0.2, position = position_dodge(width = 0.5)) +
  scale_x_discrete(labels = new_labels) +
  theme_minimal() +
  labs(x ="", y = "Estimation error", color = "Model") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=11),
    legend.position = c(0, 1),
    legend.justification = c(0, 1),
    legend.background = element_rect(
      color = "black",
      linewidth = 0.05,
      linetype = "solid"
    ),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 8),
    legend.key.size = unit(0.5, "cm"),
  ) 

ggsave("30_20_1000_v2.pdf")
```

```{r}
correct_20_10_500 <- matrix(0, nrow = 4, ncol = 3)
for (d1 in 1:4) {
  for (d2 in 1:3) {
    i <- (d1 - 1) * 3 + d2
    correct_20_10_500[d1, d2] <- sum(data_list[[i]][, c("is_correct")]) / n_row
  }
}

correct_30_20_1000 <- matrix(0, nrow = 4, ncol = 3)
for (d1 in 1:4) {
  for (d2 in 1:3) {
    i <- (d1 - 1) * 3 + d2 + 12
    correct_30_20_1000[d1, d2] <- sum(data_list[[i]][, c("is_correct")]) / n_row
  }
}

t(correct_20_10_500)
t(correct_30_20_1000)
```

